float32 t1_rpm
float32 t2_rpm 
float32 t3_rpm 
float32 t3_angle 
float32 t4_rpm
float32 t4_angle 
float32 psi_d
float32 spd_d 
float32 wp_lat_d 
float32 wp_lon_d
uint32 oper_Mode

uint32 ca_mode 
uint32 ca_method
uint32 ca_status 
float32[900] ca_risk_arr
float32 reactive_spd_d
float32 reactive_psi_d 

float32[200] track_path 
uint32 track_path_idx 

float64 surge_error
float64 sway_error
float64 yaw_error
float64 heave
float64 roll
float64 pitch
uint32 dp_start_stop

uint8[180] rx_signal