uint32 oper_mode
float32 spd_cmd
float32 hdg_cmd
float64 target_wp_lat
float64 target_wp_lon
float64 targetposition_x
float64 targetposition_y
float32 targetposition_yaw

uint32 ca_mode 
uint32 ca_method
float32 ca_alert_range 
float32 ca_avoid_range 
float32 ca_param1 
float32 ca_param2
float32 ca_param3 
float32 ca_param4 
float32 ca_param5 
float32 ca_param6 
float32 ca_param7

float32 nav_surge_pgain
float32 nav_surge_dgain 
float32 nav_yaw_pgain  
float32 nav_yaw_dgain 

float32 dp_surge_pgain
float32 dp_surge_dgain
float32 dp_sway_pgain
float32 dp_sway_dgain
float32 dp_yaw_pgain
float32 dp_yaw_dgain

float64 surge_current
float64 sway_current
float64 yaw_current
float64 heave_current
float64 roll_current
float64 pitch_current